### ISSUE TITLE
deployments.run() disables .save() inside deployment scripts

### ISSUE THREAD

**Issue by pyggie** [wighawag/buidler-deploy#2]
If you have a deployment script, say `deploy/01-Sample.ts`, and that script has code along the lines of:

```
async function deploy(bre, name) {
  const dr = await deployIfDifferent(name, ...)
  if (dr.newlyDeployed) {
    const dep = await deployments.get(name)
    deployments.save(name, dep)
  }
}
```

Then if you run `npx buidler deploy`, the `save()` operation writes to the `deployments` folder, as expected. If you run `npx buidler deploy` again (when using a non-transient network, like mainnet), the saved deployments are loaded, checked on-chain, recognized as identical, and not re-deployed. Great!

But if you call `deployments.run([name])` from a script or a test, then the contract is deployed but the `save()` operation does not write any files. Repeating the operation re-deploys the contract.

I'm not sure if this is intended, but the reason is that the `noSaving` option has default value true here:
https://github.com/wighawag/buidler-deploy/blob/b8a202ff070602d8dd1973ab9a98db58603bd708/src/DeploymentsManager.ts#L146-L155

The option is not exposed in the public type interface here:
https://github.com/wighawag/buidler-deploy/blob/b8a202ff070602d8dd1973ab9a98db58603bd708/src/type-extensions.d.ts#L73-L76

If this is all intended, then how do I achieve this pattern:
* Using a persistent network like mainnet
* `npx buidler test` deploys contracts if needed, but does not re-deploy if already existing

**Comment by wighawag** [comment]
It was indeed intended, but your issue is making reconsider :)

The idea was that test have to ensure they start on a blank state so `.run` should clear the old deployments

But now with have `deployments.fixture` which is much better than `.run` for test, I might make .run act the same in all condition. 

But actually the reset option should achieve what you want : if the reset is false, it will not redeploy if existing. At least it should not.

Re your use case, I am curious :
I suppose the test you run on the mainnet are not the same as the test you use for testing yoru contract, or at least they are a subset, right ?
Could this not be done with scripts ?

**Comment by pyggie** [comment]
> I suppose the test you run on the mainnet are not the same as the test you use for testing yoru contract, or at least they are a subset, right ? Could this not be done with scripts ?

Right, the tests I have in mind are integration tests with existing mainnet contracts. I'd like to use ganache --fork as an iterative testbed, where most of my contracts are static between test runs, but perhaps one of them changes as I make edits.
It could be done with scripts, but it's nice to use 'npx buidler test' and the mocha framework.

**Comment by pyggie** [comment]
> But actually the reset option should achieve what you want : if the reset is false, it will not redeploy if existing. At least it should not.

Hmm ... in my simple test, `deployments.run(name, { reset: false })` on a blank slate does not save any files.

But `deployments.run(name, { reset: false, noSaving: false })` does save files (after tweaking the typescript type definition to allow the option).

**Comment by pyggie** [comment]
And regardless of the reset behavior, it is definitely confusing to call

```deployments.save(name, dep)```

and it silently does nothing.

**Comment by wighawag** [comment]
ok there is a bit of confusion:

`deployments.save` do potentially 2 thing :
- save deployment in memory (useful for testing)
- save deployemnt to file (useful for live network)

reset:false will ensure memory is not cleared, it will not save to disk. 

saving to disk is currently reserved to the command `buidler deploy`

I could add the option as you did, but I though the problem was you want `npx buidler test deploys contracts if needed, but does not re-deploy if already existing`

reset should achieved that

**Comment by pyggie** [comment]
Okay, thanks for the clarification. I will use either `npx buidler deploy` or `deployments.run(name, { reset: false })` depending on the situation.

**Comment by wighawag** [comment]
new version (with breaking changes) : 0.4.1 give more options to run, see https://github.com/wighawag/buidler-deploy/blob/35c9e3b334e21e3e40850bb7aa15529d1a903199/src/type-extensions.d.ts#L123-L131

I ll close the issue, reopen if this does not solve your problem.

Thanks!
