### ISSUE TITLE
Import deployments

### ISSUE THREAD

**Issue by tuler** [wighawag/buidler-deploy#34]
The `deployments` object could provide a `deployments.import` method to import artifacts previously produced by `truffle` or even by `buidler-deploy` in another dependent project packaged as npm.

I don't know if I'm missing something about how to wire dependent projects and its artifacts.

**Comment by wighawag** [comment]
Hi, thanks for the feedback.

You can currently import deployment from other deployment manager by copying the files in `deployments` but I guess you already know that 

In any case, having it so you can import npm packages containing deployment info would be great indeed.

Do you have an example of project that release their deployment as npm package
One way I can see it working in making the `deployments` config to be an array of folder path instead of a single folder.
But more work will be required to support truffle or other format.
Actually buidler-deploy require some specific info to be present for some of its functionality so importing might cause some of these functionality to not work. But I guess a warning could be present to let users know.

**Comment by wighawag** [comment]
By the way, the title mention artifact, in buidler an artifact is only the compilation output, not a deployment
In buidler-deploy, we keep the same nomenclature: artfiact are compilation output, deployments are deployments

If you are interested in importing artifact, there is the imports folder config, but again this require you to manually copy the files you are intersted in. So I guess this feature could also benefit from multi folder and other artifact format compatibility

**Comment by tuler** [comment]
You are right, I meant deployment. But it also applies to artifacts.

It would be nice if the tag and dependencies mechanism worked cross-project.

We have this multi-project problem for quite some time now, and I hope to solve it somehow now that we are migrating our tooling to buidler.

We were using truffle, and [packing truffle build artifacts](https://github.com/cartesi/machine-solidity-step/blob/34eed873f99ace7d33da9babc895f98eaa997b14/package.json#L28) in the published npm package, which in case of truffle is the compiled artifact together with deployment information to testnets (or mainnet). We did not commit the artifacts to git, just published to npm. I think openzeppelin does the same, and ens as well.

When some other project has a contract B that depends on contract A, we have two types of dependencies. Compile time dependency, and deploy time dependency.

For compile time dependency, truffle has an issue that the artifacts in the dependent project A is not reused, so it compiles A again, producing a new artifact with no deployment information. I [opened an issue](https://github.com/trufflesuite/truffle/issues/2612) about this sometime ago.

For deployment time dependency we have two scenarios, deployment to testnets and local development deployment.

For testnets we want to [reuse the deployed](https://github.com/cartesi/machine-solidity-step/blob/34eed873f99ace7d33da9babc895f98eaa997b14/migrations/2_deploy_contracts.js#L3) already packaged in A (contract address).

For development we need to deploy a fresh A and wire to a fresh deployed B. We are doing this in a very hacky way, by [cd’ing into each dependency and running truffle migrate](https://github.com/cartesi/descartes-tutorials/blob/777c62efc8cad8658e0d696195f073c23aa1f7ad/descartes-env/deployer/migrate.sh#L10).

**Comment by wighawag** [comment]
Thanks for the extra info.
For artifact, should be pretty easy. 
For deployment, adding support for buidler-deploy generated deployment, should be easy too.
to support truffle deployment, I ll probably need to add special case for truffle. This is because truffle store the deployment in the same file for different network.
But overall the whole thing should be doable and make sense.

**Comment by wighawag** [comment]
Added that in buidler-deploy@next (0.6.0-beta.14)

See example with @cartesi/arbitration here : https://github.com/wighawag/buidler-deploy-ts-test

see config : https://github.com/wighawag/buidler-deploy-ts-test/blob/58df947153dd3b4f632c9a9876ffb441e2f1c790/buidler.config.ts#L67-L72

It supports both artifact and deployments

**Comment by wighawag** [comment]
I actually rename imports to artifacts (0.6.0-beta.15)

see : https://github.com/wighawag/buidler-deploy-ts-test/blob/1b1449dbd36d4351b03abada840273f5c63b4dd5/buidler.config.ts#L67-L72

**Comment by wighawag** [comment]
Actually I might move the network deployments to the network config object, like

```
networks: {
    extraDeployments: ["node_modules/@cartesi/arbitration/build/contracts"]
},
```

what do you think?

**Comment by tuler** [comment]
I don’t quite follow why as a network. I thought about adding to `paths`, like `externalDeployments` array of paths.

Or you could automatically support search in `node_modules` when someone “requires” a deployment by prefixing it with, I.e. `@cartesi/arbotration`. Truffle kind of does it this way.

**Comment by wighawag** [comment]
Due to https://github.com/nomiclabs/buidler/issues/776 it cannot be added on paths

And the reason I propose network is because the deployment as to be defined per network. Truffle does not support multiple set of contract per chainId but buidler-deploy does.

I thought about adding support for npm package, but this does not work if you want to link to a path that has the same name as a package. Also adding node_modules to the path is not a big deal, no ?

**Comment by tuler** [comment]
I was confused before you edited the example. Ok.

What about local development (re-)deployment? Did you think about this?

**Comment by tuler** [comment]
Related: https://github.com/nomiclabs/buidler/issues/635

**Comment by wighawag** [comment]
@tuler 
> What about local development (re-)deployment? Did you think about this?

I am not sure what you mean, but since artifact are also imported, you can deploy the contract locally too

**Comment by wighawag** [comment]
> Related: nomiclabs/buidler#635
I created that one too : https://github.com/nomiclabs/buidler/issues/520 :)

**Comment by tuler** [comment]
> I am not sure what you mean, but since artifact are also imported, you can deploy the contract locally too

Got it, I realized I just need the ABI and bytecode already in the artifact to redeploy the contract.
